services:
  e-commerce:
    image: gokulnathjd03/ecommerce:latest
    container_name: e-commerce-con
    mem_limit: 450m
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-con:3306/${SPRING_DATASOURCE_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_DATABASE: ${SPRING_DATASOURCE_DATABASE}
      REDIS_CONTAINER: redis-container
      SECRET_KEY: ${SECRET_KEY}
    ports:
      - "8081:8081"
    networks:
      - "e-commerce-network"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started

  redis:
    image: redis:alpine
    container_name: redis-container
    mem_limit: 20m
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/data"
    networks:
      - "e-commerce-network"

  mysql:
    image: mysql:8.0
    container_name: mysql-con
    mem_limit: 300m
    environment:
      MYSQL_DATABASE: ${SPRING_DATASOURCE_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${SPRING_DATASOURCE_USERNAME}
      MYSQL_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 3309:3306
    volumes:
      - ecommerce-mysql-data-new:/var/lib/mysql
    networks:
      - "e-commerce-network"

volumes:
  redis_data:
  ecommerce-mysql-data-new:

networks:
  e-commerce-network:
    driver: bridge



